{% set name = "plotapi" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6cbff01065a0fde86b9abafec0512ad024684b67d266fd3fb8392fa0a9ee23b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests >=2.20.0,<3.0.0

test:
  imports:
    - plotapi
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://plotapi.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Engaging visualisations, made easy.

extra:
  recipe-maintainers:
    - shahinrostami
