{% set name = "plotapi" %}
{% set version = "6.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa95d4616fa89cf48b62eb2605a585c2b27f6e73bd18c75505386a28a2efe28d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests >=2.20.0,<3.0.0

test:
  imports:
    - plotapi
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://plotapi.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Engaging visualisations, made easy.

extra:
  recipe-maintainers:
    - shahinrostami
